### PR TITLE
Drop OpenSSL usage and switch to sha512 for SRI calculation

### PR DESCRIPTION
**Pull request by klausenbusk**
Please note: This only affects new packages (ex: when a new version is added)

I think the easiest way to update existing SRIs, is simply "nuking" the https://github.com/cdnjs/SRIs repo (`rm */*.json && git commit -m "magic"`).

### CODE REVIEW

**Comment by xtuc** [comment]
@MattIPv4 would you mind doing the website updating part if needed?

**Comment by MattIPv4** [comment]
The website shouldn't need any change, it just pulls in whatever exists in the json files in cdnjs/sri?

**Comment by xtuc** [comment]
Yeah it doesn't I meant the names

**Comment by xtuc** [comment]
magic commit https://github.com/cdnjs/SRIs/commit/20afe2001b80c3a854d2d3fe4afb71fee02579ba

**Pull request merged**
